# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# -------------LOAD CONFIG FILE-------------
configfile: "config/config.yaml"


# -------------STEPS TO INCLUDE-------------
# include: "rules/common.smk"
include: "rules/1_get_refs.smk"


all_outputs = []

if config["get_references"]:
    all_outputs.append(get_refs_outputs)

all_outputs = flatten(all_outputs)
all_outputs = list(set(all_outputs))


# --------------RULES-------------
rule all:
    input:
        all_outputs,


# -------------LOG AND ERROR HANDLING-------------
onstart:
    print("\n--- Database build started ---\n")


onsuccess:
    print("\n--- Index complete! ---\n")


onerror:
    print("\n--- An error has occurred. ---\n")
