# Main entrypoint of the workflow.


# -------------LOAD CONFIG FILE-------------
configfile: "config/config.yaml"


# -------------STEPS TO INCLUDE-------------
include: "rules/1_acc_from_taxa.smk"
include: "rules/2_download_refs.smk"
include: "rules/3_replace_headers.smk"
include: "rules/4_acc2taxid_build.smk"


all_outputs = []

if config["get_accessions_from_taxa"]:
    all_outputs.append(acc_from_taxa_outputs)

if config["download_references"]:
    all_outputs.append(download_refs_outputs)

if config["replace_headers"]:
    all_outputs.append(replace_headers_outputs)

if config["build_acc2taxid"]:
    all_outputs.append(build_acc2taxid_outputs)

if config["build_bowtie2_index"]:
    all_outputs.append(build_bowtie2_index_outputs)

all_outputs = flatten(all_outputs)
all_outputs = list(set(all_outputs))


# --------------RULES-------------
rule all:
    input:
        all_outputs,


# -------------LOG AND ERROR HANDLING-------------
onstart:
    print("\n--- Can we build it? Database build started... ---\n")


onsuccess:
    print("\n--- YES! WE! CAN! \(^o^)/ Tasks complete. ---\n")
    if config.get("1_get_refs_stage2.smk", False):
        shell("find build/download -name '*.fna' -empty -delete || true")


onerror:
    print("\n--- No, we can't... An error has occurred. ---\n")
