executor: slurm

default-resources:
  slurm_account: "naiss2026-#-###"

set-resources:
  build_bowtie2_index:
    slurm_partition: "memory"
    mem: "1760GB"
    cpus_per_task: 128
    runtime: 7200
    slurm_extra: "'--job-name=index_build --error=logs/index_build_slurm/index_build_%A-%a.err --output=logs/index_build_slurm/index_build_%A-%a.out'"

#SBATCH -A naiss2026-4-1588 becomes slurm_account.
#SBATCH --mem=1760GB becomes mem: "1760GB" or could be expressed as mem_mb if you prefer MB units.
#Use either mem/mem_mb or mem_mb_per_cpu, not both.
#SBATCH -p memory becomes slurm_partition: "memory".
#SBATCH --cpus-per-task=128 becomes cpus_per_task: 128.
#SBATCH -t 5-00:00:00 maps to runtime, which the docs define in minutes, so 5 days is 7200 minutes.
#Extra sbatch flags can be passed with slurm_extra.

