# -------------PROJECT NAME------------- 
project_name: "test_index"

# -------------PIPELINE RESOURCES-------------
# Get References (download and unpack)
accession_list: ".test/accession_list.txt"
taxon_list: ".test/taxon_list.txt"

#-------------RULES TO USE-------------

get_references: True
