# -------------PROJECT NAME------------- 
project_name: "SE_Herps"

# -------------PIPELINE RESOURCES-------------
# Get References (download and unpack)
accession_list: ""
taxon_list: "resources/taxon_list.txt"
header_names: ""

#-------------RULES TO USE-------------

get_references: True
replace_headers: False
build_acc2taxid: False