# -------------PROJECT NAME------------- 
project_name: "BoB_test"

# -------------PIPELINE RESOURCES-------------
#Set the full paths to your input files (these may also be in the output directory).
accession_list: "full_path/to/.test/accession_list.txt"
taxon_list: "full_path/to/.test/taxon_list.txt"

#-------------RULES TO USE-------------

#Run get_accessions_from_taxa by itself first if you have a taxa_list input. Otherwise, proceed to download_references and beyond. 
get_accessions_from_taxa: True

download_references: False

#If you have decided to replace your headers, you must leave replace_headers as True when running build_acc2taxid, build_preindex_reports, and build_bowtie_index.
replace_headers: False

build_acc2taxid: False

#This rule will make 2 reports:
## a report with all the reference genomes in the index, including their full taxonomy, taxid, access number, and geographic distribution.
## an estimate of the resources needed to build the bowtie2 index, with you may use as a guide to update these settings in the profiles/config.yaml file.
build_preindex_reports: False

#Build the index when you are ready!
build_bowtie2_index:
  enabled: False
  output_dir: "full_path/to/.test/build/index" #set this to the full path of the output directory
  seed: 990412
  bowtie2_threads: 64

