# -------------PROJECT NAME------------- 
project_name: "BoB_test"

# -------------PIPELINE RESOURCES-------------
#Set the paths to your input files (these may also be in the output directory).
accession_list: ".test/accession_list.txt"
taxon_list: ".test/taxon_list.txt"

#-------------RULES TO USE-------------

get_accessions_from_taxa: True

download_references: False

replace_headers: False

#If you have decided to replace your headers, you must leave replace_headers as True when running build_acc2taxid and build_bowtie_index.
build_acc2taxid: False

